porters-xyz/gateway-demo

Dockerfile
docker-compose.yaml
gateway/db/accounts.go
gateway/db/models.go
services/postgres/schema.prisma
web-portal/backend/package.json
web-portal/backend/src/main.ts
web-portal/frontend/Dockerfile
web-portal/frontend/app/dashboard/actions.ts
web-portal/frontend/app/dashboard/logout.tsx
web-portal/frontend/app/dashboard/page.tsx
web-portal/frontend/app/login/actions.ts
web-portal/frontend/app/login/modal.component.tsx
web-portal/frontend/app/login/page.tsx

@plor I have not tested Gateway but everything on my part works i.e. FE -> BE -> Postgres

everything just works!

---

gateway/db/cache.go
gateway/db/sync.go

Playing with railway, might be a couple more of these.

Adding logging to diagnose redis connection issues

---

gateway/db/cache.go

I could just push to develop, but I like the PR history.

Using ParseURL to connect to redis by default

---

.gitmodules
docker-compose.yaml

A bit of an exploration, still testing it but we're getting there. Has a small postgres database, we may want to share postgres instance and put it on a separate database as the load should be low. I tacked the .env contents from the repo onto this project, something to track.

Testnet kit

---

docker-compose.yaml
docs/Dockerfile
docs/fly.toml
gateway/fly.toml
services/gatewaykit/README.md
services/gatewaykit/fly.toml
services/postgres/Dockerfile
services/postgres/README.md
services/redis/README.md
services/redis/fly.toml
web-portal/backend/Dockerfile
web-portal/backend/Dockerfile.fly
web-portal/backend/fly.staging.toml
web-portal/backend/fly.toml
web-portal/frontend/fly.staging.toml
web-portal/frontend/fly.toml

Adding fly configuration and made some changes to get it to work. Docs still having troubles and frontend is close. Pattern of having fly.toml and fly.staging.toml may not stick, need to figure out when github actions are set up.

Flyio init

---

docs/Dockerfile
docs/next.config.js
docs/package.json

had quite a trouble with multi-stage build for docs (nextjs 13)
- we can probably go with single stage build as not much `size` issue here of any kind

single stage build for docs

---

web-portal/backend/README.md

Migration requires running locally via fly proxy. Also ran into issue documented here.

Note about migration

---

contracts/foundry.toml
contracts/script/01_Deploy.s.sol
contracts/src/PortersUsage.sol

- script still needs work to avoid manual deploys

Deployed to sepolia, fixed a couple issues

---

contracts/README.md
docker-compose.yaml
web-portal/backend/package.json

Just a small update to work out docker compose issues (and seeds). Not sure if the seed process is kosher, so let me know.

Updating setup to run locally

---

LICENSE.txt

Hi! Could you please approve the licensing change we discussed?

added MIT licence.

---

LICENSE.txt

Thanks for spotting this @memosys .

I took that from the other repo we have in our org - tldr. mew :(

---

gateway/plugins/origin.go

Adds origin filter

---

gateway/plugins/productfilter.go

Remember to register "plugin" to use this.

Adds allowed chainlist

---

gateway/main.go
gateway/plugins/balance.go
gateway/plugins/leaky.go

minor update, I'm doing E2E and notice this issue.

Removing noop, fixing lifecycle

---

gateway/common/prometheus.go
gateway/db/models.go
gateway/db/usage.go
gateway/plugins/balance.go
gateway/proxy/proxy.go

Still working out an issue, but hoping to unblock

Changed prometheus metrics

---

web-portal/backend/package.json
web-portal/backend/src/app.module.ts
web-portal/backend/src/usage/usage.controller.spec.ts
web-portal/backend/src/usage/usage.controller.ts
web-portal/backend/src/usage/usage.module.ts
web-portal/backend/src/usage/usage.service.spec.ts
web-portal/backend/src/usage/usage.service.ts
web-portal/frontend/components/dashboard/insights.tsx
web-portal/frontend/package.json
web-portal/frontend/pages/apps/[app].tsx
web-portal/frontend/utils/atoms.ts
web-portal/frontend/utils/hooks.ts
web-portal/frontend/utils/types.ts

tackles 
#72 (some UX discussion required)
#83  (partially)
want to merge early!

Usage stuff

---

gateway/fly.prod.toml
gateway/fly.toml
gateway/justfile
justfile
services/gatewaykit/fly.prod.toml
services/gatewaykit/justfile
services/redis/fly.prod.toml
services/redis/justfile

Adding scaling commands to justfile as well. Use with caution.

Prod tweaks

---

web-portal/backend/src/app.module.ts
web-portal/backend/src/apps/apps.controller.ts
web-portal/backend/src/apps/apps.service.ts
web-portal/backend/src/decorator/public.decorator.ts
web-portal/backend/src/guards/auth.guard.ts
web-portal/backend/src/org/org.controller.ts
web-portal/backend/src/siwe/siwe.controller.ts
web-portal/backend/src/siwe/siwe.service.ts
web-portal/backend/src/tenant/tenant.controller.ts
web-portal/backend/src/usage/usage.controller.ts
web-portal/backend/src/user/user.service.ts
web-portal/backend/src/utils/utils.controller.ts
web-portal/frontend/components/dashboard/createAppModal.tsx
web-portal/frontend/utils/hooks.ts

- added global guard!
- authorization check!

added global guard etc!

---

gateway/common/tasks.go
gateway/common/tasks_test.go
gateway/db/cache.go
gateway/db/canonical.go
gateway/db/models.go
gateway/main.go
gateway/plugins/counter.go
gateway/plugins/leaky.go
gateway/proxy/error.go
gateway/proxy/health.go
gateway/proxy/lifecycle.go
gateway/proxy/proxy.go
gateway/proxy/reconciler.go

Needs some testing, a couple of added functions as part of this cleanup. Happy path works locally.

Todo cleanup

---

docker-compose.yaml
gateway/fly.toml

* also updated gatewaykit in docker-compose to match fly

Switched staging gateway url

---

web-portal/backend/src/siwe/siwe.service.ts
web-portal/frontend/components/dashboard/createAppModal.tsx
web-portal/frontend/components/dashboard/layout.tsx
web-portal/frontend/components/dashboard/logout.tsx
web-portal/frontend/components/swap/Redeem.tsx
web-portal/frontend/components/swap/Swap.tsx
web-portal/frontend/package.json
web-portal/frontend/utils/Web3Provider.tsx
web-portal/frontend/utils/hooks.ts
web-portal/frontend/utils/siwe.ts
web-portal/frontend/utils/theme.ts

- Instant Logout
- Skeleton for loading Address
- longer session (untested)
- switch chain button
- loading state
- loading state for button

ux-improvements

---

web-portal/frontend/package.json
web-portal/frontend/pages/_app.tsx
web-portal/frontend/pages/login/index.tsx
web-portal/frontend/utils/Web3Provider.tsx
web-portal/frontend/utils/siwe.ts

- fixes signout on network change
- no more connect issues

swapped out web3modal for connectkit

---

gateway/db/models.go
gateway/db/usage.go
gateway/plugins/origin.go

* also cleaning up nil pointer error that was occuring on usage

Origin introduced bug

---

gateway/common/config.go
gateway/gateway.go

Debugging on staging is better if we can adjust log level.

Change log level

---

docs/pages/For_Users/2_PORTR.md
docs/pages/For_Users/3_Application Guide.md
docs/pages/For_Users/4_Settings.md
docs/pages/For_Users/5_Swap+Redeem.md

Merging user docs updated by @boucherbox

User docs creation

---

gateway/common/config.go
gateway/proxy/kitMetricsKitRouter.go
gateway/proxy/mux.go

This tightly couples the deployment to fly.io, but we can improve on this later

added fly.io regional metrics capture for poktscan.

---

.github/workflows/proxy-prod.yml
gateway/fly.prod.toml

This is to avoid reliability issues being currently experienced

Defined schedule for porters proxy to reboot every 4 hrs
